---
spring:
  profiles: int
mesos:
  master: zk://10.40.131.24:2181,10.40.139.50:2181,10.40.135.54:2181/mesos

scoring:
  host: http://spring-scoring01.int.io/v1
  clientId: AOZ
  clientSecret: AOF

kinesis:
  applicationName: io.application
  streamName: io.score
  region: us-east-1
  partitionKey: partitionKey

aws:
  arn: arn:aws:iam::187:role/io.score.local
  accountId: 187
  sessionTokenDurationSeconds: 3600

assignments:
  host: http://int.com/assignments/v2
  clientId: TS0
  clientSecret: d5q

retry:
  limit:
    mesos: 5
    benchmarkTask: 5
  waitIntercept: 1000
  waitSlope: 1000

---
spring:
  profiles: cert
mesos:
  master: zk://10.40.131.24:2181,10.40.139.50:2181,10.40.135.54:2181/mesos

scoring:
  host: https://spring-scoring01.cert.io/v1
  clientId: AOZ
  clientSecret: AOF

kinesis:
  applicationName: io.score.application
  streamName: io.cert.kinesis.score
  region: us-east-1
  partitionKey: partitionKey

aws:
  arn: arn:aws:iam::187:role/io.cert.score.local
  accountId: 187
  sessionTokenDurationSeconds: 3600

assignments:
  host: https://cert.com/v2
  clientId: TS0
  clientSecret: d5q

retry:
  limit:
    mesos: 5
    benchmarkTask: 5
  waitIntercept: 1000
  waitSlope: 1000
---
spring:
  profiles: certrv
mesos:
  master: zk://10.40.131.24:2181,10.40.139.50:2181,10.40.135.54:2181/mesos

scoring:
  host: https://spring-scoring01.certrv/v1
  clientId: AOZ
  clientSecret: AOF

kinesis:
  applicationName: io.certrv.application
  streamName: io.certrv.kinesis.score
  region: us-east-1
  partitionKey: partitionKey

aws:
  arn: arn:aws:iam::187:role/io.certrv.score.local
  accountId: 187
  sessionTokenDurationSeconds: 3600

assignments:
  host: https://certrv.com/v2
  clientId: TS0
  clientSecret: d5q

retry:
  limit:
    mesos: 5
    benchmarkTask: 5
  waitIntercept: 1000
  waitSlope: 1000
---
spring:
  profiles: local
mesos:
  master: 127.0.0.1:5050

scoring:
  host: http://spring-scoring01.dev./v1
  clientId: AOZ
  clientSecret: AOF

kinesis:
  applicationName: io.dev.score.application
  streamName: io.dev.kinesis.score
  region: us-east-1
  partitionKey: partitionKey

aws:
  arn: arn:aws:iam::187:role/io.dev.score.local
  accountId: 187
  sessionTokenDurationSeconds: 3600

assignments:
  host: http://int.asmtone.api.com/assignments/v2
  clientId: TS0
  clientSecret: d5q

retry:
  limit:
    mesos: 5
    benchmarkTask: 5
  waitIntercept: 1000
  waitSlope: 1000
---
spring:
  profiles: prod
mesos:
  master: zk://10.40.119.63:2181,10.40.123.13:2181,10.40.115.41:2181/mesos

scoring:
  host: https://spring-scoring01.io/v1
  clientId: AOZ
  clientSecret: AOF

kinesis:
  applicationName: io.prod.score.application
  streamName: io.prod.kinesis.score
  region: us-east-1
  partitionKey: partitionKey

aws:
  arn: arn:aws:iam::744:role/io.prod.score.local
  accountId: 744
  sessionTokenDurationSeconds: 3600

assignments:
  host: https://www.h.com/api/assig/v2
  clientId: TS0
  clientSecret: d5q

retry:
  limit:
    mesos: 5
    benchmarkTask: 5
  waitIntercept: 1000
  waitSlope: 1000
